{
 "title": "Data Pipeline & Kafka Dashboard",
 "tags": [
  "kafka",
  "pipeline",
  "minio"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Kafka & Ingestion (Data-Core)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Traités / Minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_fetch_manager_records_consumed_total{job=\"spring-boot-worker\"}[1m]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Consumer Lag (Fichiers en attente)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_consumer_fetch_manager_records_lag_max{job=\"spring-boot-worker\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "title": "Temps de traitement moyen par fichier",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spring_kafka_listener_seconds_sum{job=\"spring-boot-worker\"}[1m])) / sum(rate(spring_kafka_listener_seconds_count{job=\"spring-boot-worker\"}[1m]))",
     "legendFormat": "Durée moyenne de traitement"
    }
   ]
  },
  { "title": "Santé Système (Worker & MinIO)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Worker JVM Memory (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", job=\"spring-boot-worker\"}",
     "legendFormat": "RAM Utilisée"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", job=\"spring-boot-worker\"}",
     "legendFormat": "RAM Maximum Allouée"
    }
   ]
  },
  {
   "title": "Worker CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"spring-boot-worker\"}",
     "legendFormat": "CPU Worker"
    }
   ]
  }
 ]
}